// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using webapi.DataAccess;

#nullable disable

namespace webapi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240131205318_V0.1UserSeed")]
    partial class V01UserSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SubjectUser", b =>
                {
                    b.Property<int>("UsersId")
                        .HasColumnType("int");

                    b.Property<string>("SubjectsEnumSubject")
                        .HasColumnType("nvarchar(450)");

                    b.Property<short>("SubjectsLevel")
                        .HasColumnType("smallint");

                    b.Property<int>("SubjectsId")
                        .HasColumnType("int");

                    b.HasKey("UsersId", "SubjectsEnumSubject", "SubjectsLevel", "SubjectsId");

                    b.HasIndex("SubjectsEnumSubject", "SubjectsLevel", "SubjectsId");

                    b.ToTable("SubjectUser");
                });

            modelBuilder.Entity("webapi.Object.Subject", b =>
                {
                    b.Property<string>("EnumSubject")
                        .HasColumnType("nvarchar(450)");

                    b.Property<short>("Level")
                        .HasColumnType("smallint");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastUpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("EnumSubject", "Level", "Id");

                    b.ToTable("Subject");

                    b.HasData(
                        new
                        {
                            EnumSubject = "ENGLISH",
                            Level = (short)3,
                            Id = 1,
                            CreatedDate = new DateTime(2024, 1, 31, 21, 53, 18, 85, DateTimeKind.Local).AddTicks(8605)
                        },
                        new
                        {
                            EnumSubject = "ENGLISH",
                            Level = (short)4,
                            Id = 2,
                            CreatedDate = new DateTime(2024, 1, 31, 21, 53, 18, 85, DateTimeKind.Local).AddTicks(8693)
                        },
                        new
                        {
                            EnumSubject = "ENGLISH",
                            Level = (short)5,
                            Id = 3,
                            CreatedDate = new DateTime(2024, 1, 31, 21, 53, 18, 85, DateTimeKind.Local).AddTicks(8715)
                        },
                        new
                        {
                            EnumSubject = "ENGLISH",
                            Level = (short)6,
                            Id = 4,
                            CreatedDate = new DateTime(2024, 1, 31, 21, 53, 18, 85, DateTimeKind.Local).AddTicks(8735)
                        },
                        new
                        {
                            EnumSubject = "MATH",
                            Level = (short)3,
                            Id = 5,
                            CreatedDate = new DateTime(2024, 1, 31, 21, 53, 18, 85, DateTimeKind.Local).AddTicks(8757)
                        },
                        new
                        {
                            EnumSubject = "MATH",
                            Level = (short)4,
                            Id = 6,
                            CreatedDate = new DateTime(2024, 1, 31, 21, 53, 18, 85, DateTimeKind.Local).AddTicks(8779)
                        },
                        new
                        {
                            EnumSubject = "MATH",
                            Level = (short)5,
                            Id = 7,
                            CreatedDate = new DateTime(2024, 1, 31, 21, 53, 18, 85, DateTimeKind.Local).AddTicks(8799)
                        },
                        new
                        {
                            EnumSubject = "MATH",
                            Level = (short)6,
                            Id = 8,
                            CreatedDate = new DateTime(2024, 1, 31, 21, 53, 18, 85, DateTimeKind.Local).AddTicks(8818)
                        },
                        new
                        {
                            EnumSubject = "HISTORY",
                            Level = (short)3,
                            Id = 9,
                            CreatedDate = new DateTime(2024, 1, 31, 21, 53, 18, 85, DateTimeKind.Local).AddTicks(8839)
                        },
                        new
                        {
                            EnumSubject = "HISTORY",
                            Level = (short)4,
                            Id = 10,
                            CreatedDate = new DateTime(2024, 1, 31, 21, 53, 18, 85, DateTimeKind.Local).AddTicks(8860)
                        },
                        new
                        {
                            EnumSubject = "HISTORY",
                            Level = (short)5,
                            Id = 11,
                            CreatedDate = new DateTime(2024, 1, 31, 21, 53, 18, 85, DateTimeKind.Local).AddTicks(8880)
                        },
                        new
                        {
                            EnumSubject = "HISTORY",
                            Level = (short)6,
                            Id = 12,
                            CreatedDate = new DateTime(2024, 1, 31, 21, 53, 18, 85, DateTimeKind.Local).AddTicks(8900)
                        },
                        new
                        {
                            EnumSubject = "GEOGRAPHY",
                            Level = (short)3,
                            Id = 13,
                            CreatedDate = new DateTime(2024, 1, 31, 21, 53, 18, 85, DateTimeKind.Local).AddTicks(8964)
                        },
                        new
                        {
                            EnumSubject = "GEOGRAPHY",
                            Level = (short)4,
                            Id = 14,
                            CreatedDate = new DateTime(2024, 1, 31, 21, 53, 18, 85, DateTimeKind.Local).AddTicks(8988)
                        },
                        new
                        {
                            EnumSubject = "GEOGRAPHY",
                            Level = (short)5,
                            Id = 15,
                            CreatedDate = new DateTime(2024, 1, 31, 21, 53, 18, 85, DateTimeKind.Local).AddTicks(9008)
                        },
                        new
                        {
                            EnumSubject = "GEOGRAPHY",
                            Level = (short)6,
                            Id = 16,
                            CreatedDate = new DateTime(2024, 1, 31, 21, 53, 18, 85, DateTimeKind.Local).AddTicks(9028)
                        },
                        new
                        {
                            EnumSubject = "SCIENCE",
                            Level = (short)3,
                            Id = 17,
                            CreatedDate = new DateTime(2024, 1, 31, 21, 53, 18, 85, DateTimeKind.Local).AddTicks(9050)
                        },
                        new
                        {
                            EnumSubject = "SCIENCE",
                            Level = (short)4,
                            Id = 18,
                            CreatedDate = new DateTime(2024, 1, 31, 21, 53, 18, 85, DateTimeKind.Local).AddTicks(9071)
                        },
                        new
                        {
                            EnumSubject = "SCIENCE",
                            Level = (short)5,
                            Id = 19,
                            CreatedDate = new DateTime(2024, 1, 31, 21, 53, 18, 85, DateTimeKind.Local).AddTicks(9091)
                        },
                        new
                        {
                            EnumSubject = "SCIENCE",
                            Level = (short)6,
                            Id = 20,
                            CreatedDate = new DateTime(2024, 1, 31, 21, 53, 18, 85, DateTimeKind.Local).AddTicks(9110)
                        },
                        new
                        {
                            EnumSubject = "PHYSICS",
                            Level = (short)3,
                            Id = 21,
                            CreatedDate = new DateTime(2024, 1, 31, 21, 53, 18, 85, DateTimeKind.Local).AddTicks(9131)
                        },
                        new
                        {
                            EnumSubject = "PHYSICS",
                            Level = (short)4,
                            Id = 22,
                            CreatedDate = new DateTime(2024, 1, 31, 21, 53, 18, 85, DateTimeKind.Local).AddTicks(9151)
                        },
                        new
                        {
                            EnumSubject = "PHYSICS",
                            Level = (short)5,
                            Id = 23,
                            CreatedDate = new DateTime(2024, 1, 31, 21, 53, 18, 85, DateTimeKind.Local).AddTicks(9171)
                        },
                        new
                        {
                            EnumSubject = "PHYSICS",
                            Level = (short)6,
                            Id = 24,
                            CreatedDate = new DateTime(2024, 1, 31, 21, 53, 18, 85, DateTimeKind.Local).AddTicks(9191)
                        },
                        new
                        {
                            EnumSubject = "CHEMISTRY",
                            Level = (short)3,
                            Id = 25,
                            CreatedDate = new DateTime(2024, 1, 31, 21, 53, 18, 85, DateTimeKind.Local).AddTicks(9212)
                        },
                        new
                        {
                            EnumSubject = "CHEMISTRY",
                            Level = (short)4,
                            Id = 26,
                            CreatedDate = new DateTime(2024, 1, 31, 21, 53, 18, 85, DateTimeKind.Local).AddTicks(9232)
                        },
                        new
                        {
                            EnumSubject = "CHEMISTRY",
                            Level = (short)5,
                            Id = 27,
                            CreatedDate = new DateTime(2024, 1, 31, 21, 53, 18, 85, DateTimeKind.Local).AddTicks(9252)
                        },
                        new
                        {
                            EnumSubject = "CHEMISTRY",
                            Level = (short)6,
                            Id = 28,
                            CreatedDate = new DateTime(2024, 1, 31, 21, 53, 18, 85, DateTimeKind.Local).AddTicks(9271)
                        },
                        new
                        {
                            EnumSubject = "BIOLOGY",
                            Level = (short)3,
                            Id = 29,
                            CreatedDate = new DateTime(2024, 1, 31, 21, 53, 18, 85, DateTimeKind.Local).AddTicks(9292)
                        },
                        new
                        {
                            EnumSubject = "BIOLOGY",
                            Level = (short)4,
                            Id = 30,
                            CreatedDate = new DateTime(2024, 1, 31, 21, 53, 18, 85, DateTimeKind.Local).AddTicks(9312)
                        },
                        new
                        {
                            EnumSubject = "BIOLOGY",
                            Level = (short)5,
                            Id = 31,
                            CreatedDate = new DateTime(2024, 1, 31, 21, 53, 18, 85, DateTimeKind.Local).AddTicks(9332)
                        },
                        new
                        {
                            EnumSubject = "BIOLOGY",
                            Level = (short)6,
                            Id = 32,
                            CreatedDate = new DateTime(2024, 1, 31, 21, 53, 18, 85, DateTimeKind.Local).AddTicks(9352)
                        },
                        new
                        {
                            EnumSubject = "PHILOSOPHY",
                            Level = (short)3,
                            Id = 33,
                            CreatedDate = new DateTime(2024, 1, 31, 21, 53, 18, 85, DateTimeKind.Local).AddTicks(9373)
                        },
                        new
                        {
                            EnumSubject = "PHILOSOPHY",
                            Level = (short)4,
                            Id = 34,
                            CreatedDate = new DateTime(2024, 1, 31, 21, 53, 18, 85, DateTimeKind.Local).AddTicks(9394)
                        },
                        new
                        {
                            EnumSubject = "PHILOSOPHY",
                            Level = (short)5,
                            Id = 35,
                            CreatedDate = new DateTime(2024, 1, 31, 21, 53, 18, 85, DateTimeKind.Local).AddTicks(9413)
                        },
                        new
                        {
                            EnumSubject = "PHILOSOPHY",
                            Level = (short)6,
                            Id = 36,
                            CreatedDate = new DateTime(2024, 1, 31, 21, 53, 18, 85, DateTimeKind.Local).AddTicks(9432)
                        },
                        new
                        {
                            EnumSubject = "ART",
                            Level = (short)3,
                            Id = 37,
                            CreatedDate = new DateTime(2024, 1, 31, 21, 53, 18, 85, DateTimeKind.Local).AddTicks(9453)
                        },
                        new
                        {
                            EnumSubject = "ART",
                            Level = (short)4,
                            Id = 38,
                            CreatedDate = new DateTime(2024, 1, 31, 21, 53, 18, 85, DateTimeKind.Local).AddTicks(9507)
                        },
                        new
                        {
                            EnumSubject = "ART",
                            Level = (short)5,
                            Id = 39,
                            CreatedDate = new DateTime(2024, 1, 31, 21, 53, 18, 85, DateTimeKind.Local).AddTicks(9530)
                        },
                        new
                        {
                            EnumSubject = "ART",
                            Level = (short)6,
                            Id = 40,
                            CreatedDate = new DateTime(2024, 1, 31, 21, 53, 18, 85, DateTimeKind.Local).AddTicks(9550)
                        },
                        new
                        {
                            EnumSubject = "MUSIC",
                            Level = (short)3,
                            Id = 41,
                            CreatedDate = new DateTime(2024, 1, 31, 21, 53, 18, 85, DateTimeKind.Local).AddTicks(9572)
                        },
                        new
                        {
                            EnumSubject = "MUSIC",
                            Level = (short)4,
                            Id = 42,
                            CreatedDate = new DateTime(2024, 1, 31, 21, 53, 18, 85, DateTimeKind.Local).AddTicks(9591)
                        },
                        new
                        {
                            EnumSubject = "MUSIC",
                            Level = (short)5,
                            Id = 43,
                            CreatedDate = new DateTime(2024, 1, 31, 21, 53, 18, 85, DateTimeKind.Local).AddTicks(9611)
                        },
                        new
                        {
                            EnumSubject = "MUSIC",
                            Level = (short)6,
                            Id = 44,
                            CreatedDate = new DateTime(2024, 1, 31, 21, 53, 18, 85, DateTimeKind.Local).AddTicks(9631)
                        },
                        new
                        {
                            EnumSubject = "SPORT",
                            Level = (short)3,
                            Id = 45,
                            CreatedDate = new DateTime(2024, 1, 31, 21, 53, 18, 85, DateTimeKind.Local).AddTicks(9652)
                        },
                        new
                        {
                            EnumSubject = "SPORT",
                            Level = (short)4,
                            Id = 46,
                            CreatedDate = new DateTime(2024, 1, 31, 21, 53, 18, 85, DateTimeKind.Local).AddTicks(9672)
                        },
                        new
                        {
                            EnumSubject = "SPORT",
                            Level = (short)5,
                            Id = 47,
                            CreatedDate = new DateTime(2024, 1, 31, 21, 53, 18, 85, DateTimeKind.Local).AddTicks(9692)
                        },
                        new
                        {
                            EnumSubject = "SPORT",
                            Level = (short)6,
                            Id = 48,
                            CreatedDate = new DateTime(2024, 1, 31, 21, 53, 18, 85, DateTimeKind.Local).AddTicks(9711)
                        },
                        new
                        {
                            EnumSubject = "COMPUTER_SCIENCE",
                            Level = (short)3,
                            Id = 49,
                            CreatedDate = new DateTime(2024, 1, 31, 21, 53, 18, 85, DateTimeKind.Local).AddTicks(9732)
                        },
                        new
                        {
                            EnumSubject = "COMPUTER_SCIENCE",
                            Level = (short)4,
                            Id = 50,
                            CreatedDate = new DateTime(2024, 1, 31, 21, 53, 18, 85, DateTimeKind.Local).AddTicks(9752)
                        },
                        new
                        {
                            EnumSubject = "COMPUTER_SCIENCE",
                            Level = (short)5,
                            Id = 51,
                            CreatedDate = new DateTime(2024, 1, 31, 21, 53, 18, 85, DateTimeKind.Local).AddTicks(9772)
                        },
                        new
                        {
                            EnumSubject = "COMPUTER_SCIENCE",
                            Level = (short)6,
                            Id = 52,
                            CreatedDate = new DateTime(2024, 1, 31, 21, 53, 18, 85, DateTimeKind.Local).AddTicks(9792)
                        },
                        new
                        {
                            EnumSubject = "FRENCH",
                            Level = (short)3,
                            Id = 53,
                            CreatedDate = new DateTime(2024, 1, 31, 21, 53, 18, 85, DateTimeKind.Local).AddTicks(9814)
                        },
                        new
                        {
                            EnumSubject = "FRENCH",
                            Level = (short)4,
                            Id = 54,
                            CreatedDate = new DateTime(2024, 1, 31, 21, 53, 18, 85, DateTimeKind.Local).AddTicks(9833)
                        },
                        new
                        {
                            EnumSubject = "FRENCH",
                            Level = (short)5,
                            Id = 55,
                            CreatedDate = new DateTime(2024, 1, 31, 21, 53, 18, 85, DateTimeKind.Local).AddTicks(9853)
                        },
                        new
                        {
                            EnumSubject = "FRENCH",
                            Level = (short)6,
                            Id = 56,
                            CreatedDate = new DateTime(2024, 1, 31, 21, 53, 18, 85, DateTimeKind.Local).AddTicks(9873)
                        },
                        new
                        {
                            EnumSubject = "SPANISH",
                            Level = (short)3,
                            Id = 57,
                            CreatedDate = new DateTime(2024, 1, 31, 21, 53, 18, 85, DateTimeKind.Local).AddTicks(9894)
                        },
                        new
                        {
                            EnumSubject = "SPANISH",
                            Level = (short)4,
                            Id = 58,
                            CreatedDate = new DateTime(2024, 1, 31, 21, 53, 18, 85, DateTimeKind.Local).AddTicks(9914)
                        },
                        new
                        {
                            EnumSubject = "SPANISH",
                            Level = (short)5,
                            Id = 59,
                            CreatedDate = new DateTime(2024, 1, 31, 21, 53, 18, 85, DateTimeKind.Local).AddTicks(9933)
                        },
                        new
                        {
                            EnumSubject = "SPANISH",
                            Level = (short)6,
                            Id = 60,
                            CreatedDate = new DateTime(2024, 1, 31, 21, 53, 18, 85, DateTimeKind.Local).AddTicks(9953)
                        });
                });

            modelBuilder.Entity("webapi.Object.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastUpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pseudo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 1, 31, 21, 53, 18, 85, DateTimeKind.Local).AddTicks(9981),
                            Email = "Email@de.Test",
                            FirstName = "PrenomDeTest",
                            LastName = "NomDeTest",
                            Password = "test",
                            Pseudo = "PseudoDeTest"
                        });
                });

            modelBuilder.Entity("SubjectUser", b =>
                {
                    b.HasOne("webapi.Object.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("webapi.Object.Subject", null)
                        .WithMany()
                        .HasForeignKey("SubjectsEnumSubject", "SubjectsLevel", "SubjectsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
